plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.userxx09afk.myq'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.userxx09afk.myq'
        minSdk 30          // Wear OS 3+
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.wear:wear:1.3.0'
}
